# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
 if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
end

 config.vm.define :servidorRest do |servidorRest|
  servidorRest.vm.box = "generic/centos9s"
  servidorRest.vm.network :private_network, ip: "192.168.60.3"
  servidorRest.vm.hostname = "servidorRest"
end

 config.vm.define :servidor1 do |servidor1|
  servidor1.vm.box = "generic/centos9s"
  servidor1.vm.network "public_network"
  servidor1.vm.network :private_network, ip: "192.168.60.4"
  servidor1.vm.hostname = "servidor1"
end

 config.vm.define :servidor2 do |servidor2|
  servidor2.vm.box = "generic/centos9s"
  servidor2.vm.network "public_network"
  servidor2.vm.network :private_network, ip: "192.168.60.2"
  servidor2.vm.hostname = "servidor2"
end
end
